#!/usr/bin/env perl

use autodie;
use Modern::Perl;

my %redirects;

open my $fh, '<', 'redirects';
for my $line (<$fh>) {
    chomp $line;

    if ($line =~ /^(\S+)\s+(\S+)$/) {
        $redirects{$1} = $2;
    }
}
close $fh;

for my $file (@ARGV) {
    open my $fh, '<', $file;

    my $s = do { local $/ = <$fh> };
    close $fh;

    # Replace depcrated <center>
    $s =~ s|<center>(.+?)</center>|<div class="center">$1</div>|sg;

    while (my ($old, $new) = each %redirects) {
        $s =~ s|\Q$old\E|$new|gi;
    }

    open $fh, '>', $file;
    print $fh $s;
}

